export const CONVERT_LIST = [
  {
    value: 1,
    name: "방 크기",
    list: [{ name: "평" }, { name: "제곱미터" }],
  },
  {
    value: 2,
    name: "길이",
    list: [
      { name: "미리미터" },
      { name: "센티미터" },
      { name: "미터" },
      { name: "키로미터" },
      { name: "마일" },
      { name: "마이크로미터" },
      { name: "나노미터" },
      { name: "피트" },
      { name: "인치" },
      { name: "해리" },
    ],
  },
  {
    value: 3,
    name: "데이터 크기",
    list: [
      { name: "비트" },
      { name: "킬로비트" },
      { name: "메가비트" },
      { name: "메비비트" },
      { name: "기가비트" },
      { name: "테라비트" },
      { name: "테비비트" },
      { name: "페타비트" },
      { name: "페비비트" },
      { name: "-----------------" },
      { name: "바이트" },
      { name: "킬로바이트" },
      { name: "메가바이트" },
      { name: "메비바이트" },
      { name: "기가바이트" },
      { name: "테라바이트" },
      { name: "테비바이트" },
      { name: "페타바이트" },
      { name: "페비바이트" },
    ],
  },
];
